/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#75777d',
        'on-tertiary-fixed-variant': '#6e3900',
        'on-tertiary': '#ffffff',
        'on-background': '#0d1c2e',
        'on-error-container': '#93000a',
        'surface-tint': '#545f73',
        'on-surface': '#0d1c2e',
        'tertiary-fixed': '#ffdcc3',
        'secondary-container': '#316bf3',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#ccdbf3',
        primary: '#091426',
        'on-secondary-container': '#fefcff',
        'surface-container-highest': '#d5e3fc',
        'error-container': '#ffdad6',
        tertiary: '#240f00',
        'on-tertiary-fixed': '#2f1500',
        'on-error': '#ffffff',
        'surface-container': '#e6eeff',
        'surface-container-low': '#eff4ff',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-variant': '#d5e3fc',
        secondary: '#0051d5',
        'on-surface-variant': '#45474c',
        'inverse-on-surface': '#eaf1ff',
        'primary-container': '#1e293b',
        'primary-fixed-dim': '#bcc7de',
        surface: '#f8f9ff',
        'on-secondary-fixed-variant': '#003ea8',
        'on-secondary': '#ffffff',
        background: '#f8f9ff',
        'on-primary-fixed': '#111c2d',
        'outline-variant': '#c5c6cd',
        'on-tertiary-container': '#d97705',
        error: '#ba1a1a',
        'inverse-primary': '#bcc7de',
        'on-secondary-fixed': '#00174b',
        'primary-fixed': '#d8e3fb',
        'secondary-fixed': '#dbe1ff',
        'on-primary-container': '#8590a6',
        'on-primary-fixed-variant': '#3c475a',
        'on-primary': '#ffffff',
        'tertiary-container': '#422000',
        'inverse-surface': '#233144',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#ffb77d',
        'surface-container-high': '#dce9ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'ledger-width': '1280px',
        'reading-measure': '68ch',
        'step-lg': '1.5rem',
        'step-sm': '0.5rem',
        'step-md': '0.75rem',
        'step-xs': '0.25rem',
        'step-2xl': '3rem',
        'column-gap': '1.5rem',
        'step-xl': '2rem',
        'step-base': '1rem',
        'step-3xl': '4.5rem',
        'step-xxs': '0.125rem',
      },
      fontFamily: {
        'body-md': ['Newsreader'],
        'body-lg': ['Newsreader'],
        'caption-italic': ['Newsreader'],
        'headline-sm': ['Newsreader'],
        'label-data-sm': ['JetBrains Mono'],
        'label-data-md': ['JetBrains Mono'],
        'display-xl': ['Newsreader'],
        'headline-lg-mobile': ['Newsreader'],
        'label-data-lg': ['JetBrains Mono'],
        'body-sm': ['Newsreader'],
        'headline-md': ['Newsreader'],
        'display-xl-mobile': ['Newsreader'],
        'headline-lg': ['Newsreader'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-lg': ['19px', { lineHeight: '30px', fontWeight: '400' }],
        'caption-italic': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-data-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-data-md': ['12px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-xl': ['52px', { lineHeight: '60px', letterSpacing: '-0.025em', fontWeight: '400' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-data-lg': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'display-xl-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
