import { useCallback, useEffect, useRef, useState } from 'react';
import { getPresets, health, runExperiment, runPreset } from '../api/experiments';
import type { ApiPreset, ExperimentConfig, ExperimentResponse, TraceItem } from '../types/experiment';
const initialConfig: ExperimentConfig = { seqLen:16, slotsK:16, interference:0, seed:42, targetVal:7, targetPos:0, queryPos:15, vocabularySize:20 };
const toRequest=(c:ExperimentConfig)=>({sequence_length:c.seqLen,memory_slots:c.slotsK,vocabulary_size:c.vocabularySize,target_token:c.targetVal,interference:c.interference,seed:c.seed,target_position:c.targetPos,query_position:c.queryPos});
const fromResult=(r:ExperimentResponse):ExperimentConfig=>({seqLen:r.parameters.sequence_length,slotsK:r.parameters.memory_slots,vocabularySize:r.parameters.vocabulary_size,targetVal:r.parameters.target_token,interference:r.parameters.interference,seed:r.seed,targetPos:r.ground_truth.target_position,queryPos:r.ground_truth.query_position});
export interface UseExperimentResult { config:ExperimentConfig;result:ExperimentResponse|null;presets:ApiPreset[];backendOnline:boolean;loading:boolean;error:string|null;currentStep:number;currentTrace:TraceItem|null;isPlaying:boolean;speed:number;setSpeed:(n:number)=>void;play:()=>void;pause:()=>void;togglePlay:()=>void;stepForward:()=>void;stepBack:()=>void;reset:()=>void;runWithConfig:(c:ExperimentConfig)=>Promise<void>;runPreset:(n:string)=>Promise<void>; }
export function useExperiment():UseExperimentResult {
 const [config,setConfig]=useState(initialConfig),[result,setResult]=useState<ExperimentResponse|null>(null),[presets,setPresets]=useState<ApiPreset[]>([]),[backendOnline,setOnline]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[currentStep,setStep]=useState(0),[isPlaying,setPlaying]=useState(false),[speed,setSpeed]=useState(1); const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const pause=useCallback(()=>{setPlaying(false);if(timer.current)clearInterval(timer.current);timer.current=null;},[]);
 const apply=useCallback((r:ExperimentResponse)=>{pause();setResult(r);setConfig(fromResult(r));setStep(0);setError(null);},[pause]);
 const runWithConfig=useCallback(async(c:ExperimentConfig)=>{setLoading(true);setError(null);try{apply(await runExperiment(toRequest(c)));}catch(e){setError(e instanceof Error?e.message:'Experiment request failed.');}finally{setLoading(false);}},[apply]);
 const runNamedPreset=useCallback(async(n:string)=>{setLoading(true);setError(null);try{apply(await runPreset(n));}catch(e){setError(e instanceof Error?e.message:'Preset request failed.');}finally{setLoading(false);}},[apply]);
 useEffect(()=>{let active=true;(async()=>{try{await health();if(!active)return;setOnline(true);const p=await getPresets();if(!active)return;setPresets(p);const d=p.find(x=>x.name==='baseline')??p[0];if(d)await runNamedPreset(d.name);else setLoading(false);}catch(e){if(active){setOnline(false);setError(e instanceof Error?e.message:'Backend unavailable.');setLoading(false);}}})();return()=>{active=false;};},[runNamedPreset]);
 const total=result?.memory_trace.length??0; useEffect(()=>{if(!isPlaying)return;timer.current=setInterval(()=>setStep(s=>{if(s>=total){setPlaying(false);return s;}return s+1;}),Math.max(80,800/speed));return()=>{if(timer.current)clearInterval(timer.current);};},[isPlaying,speed,total]); const play=useCallback(()=>{if(currentStep<total)setPlaying(true);},[currentStep,total]);
 return {config,result,presets,backendOnline,loading,error,currentStep,currentTrace:currentStep>0?result?.memory_trace[currentStep-1]??null:null,isPlaying,speed,setSpeed,play,pause,togglePlay:()=>isPlaying?pause():play(),stepForward:()=>setStep(s=>Math.min(total,s+1)),stepBack:()=>setStep(s=>Math.max(0,s-1)),reset:()=>{pause();setStep(0);},runWithConfig,runPreset:runNamedPreset};
}
